### ISSUE TITLE
F-droid version

### ISSUE THREAD

**Issue by dittaeva** [avram/zandy#132]
[F-droid](http://f-droid.org) [isn't compiling new versions of Zandy](https://f-droid.org/wiki/page/com.gimranov.zandy.app) because it pulls in unfree binaries; crashlytics, swing (at least that is the concern with crashlytics).

F-droid is a really great market, and is gaining steam and quality, and it would really be great to have Zandy included. Would it be possible to make a f-droid branch, like [aLogCatRoot has done](https://github.com/pedja1/aLogcatRoot/issues/1)?

**Comment by avram** [comment]
I don't want a separate branch, but I wouldn't be opposed to finding a way to make the dependencies conditional on the build environment -- does F-Droid do anything like set an environment variable during the build which I could use to make the build script suppress its dependencies in that case?

**Comment by dittaeva** [comment]
There's [plenty of options available for the build process](https://f-droid.org/manual/fdroid.html#Build), so yes, I suppose `init` or `prebuild` could be used (?), but perhaps you'll find a better option to use.

**Comment by martinruenz** [comment]
Further F-Droid support would indeed be awesome!
I'm stuck with version 1.3.7 and it keeps crashing before I can log in ;-(

**Comment by itayshom** [comment]
Hi,
I would also like to join the request for an F-droid version. That's the only market I use, and it's still version 1.3.7... I'm sure this will greatly increase Zandy's userbase.

**Comment by BenjaminHCCarr** [comment]
I see you pulled some of the zotable code, do you plan on continuing this code base? Or should we work on building/adding the zotable source to F-Droid?

**Comment by avram** [comment]
I made that PR primarily for visibility. As for f-droid, I'm still not
planning on revisiting the build to make that work, but I'd someone has a
PR to make it work with that market, I'd be amenable to it

**Comment by avram** [comment]
Looks like F-droid picked it up again
