### ISSUE TITLE
Missing items and collections

### ISSUE THREAD

**Issue by jluttine** [avram/zandy#133]
I have some items and collections missing in Zandy. They are available on my computers with firefox+zotero. In addition, some items are not shown all collections they belong to. For instance, one item is show in only two collections although it is really in three (all these collections are in zandy). 

Also, "View Collections" shows incorrect number of items for most collections. It shows 0 items for most and "Stale data". When clicked, the items are shown (at least those that are not missing from Zandy). If clicking "Sync" in such a collection, I get an error "Unfortunately, Zandy has stopped" and Zandy restarts. This happens with collections that are shown 0 items although they have items.

I suppose all these problems are caused by some invalid data in some items. Any ideas?

I'm using Zandy 1.3.7 from F-Droid.

**Comment by avram** [comment]
It could certainly even be something fixed in the subsequent releases of Zandy-- can you build it locally?

**Comment by jluttine** [comment]
I have no experience in building software for Android, so I'm not eager to do that. But if there are good instructions somewhere, I could try. I hope more recent versions become available via F-Droid too.

**Comment by avram** [comment]
Merging with #132 and closing
