### ISSUE TITLE
General Lint cleanup

### ISSUE THREAD

**Issue by judeibe** [avram/zandy#149]

**Comment by avram** [comment]
Thanks for all your support!

You don't need to create an issue for each PR- just open the PR unless it needs discussion prior to writing code.

**Comment by judeibe** [comment]
Habit, was following some guidelines of bigger projects. Ill do so for others.

**Comment by avram** [comment]
Yeah - bigger projects tend to operate in that fashion. This is a pretty small affair! Welcome back to the project.
