### ISSUE TITLE
Zotero articles get duplicated

### ISSUE THREAD

**Issue by AhthaVan** [avram/zandy#90]
When I give read/write access to my zandy API key, I found that articles I visited with Zandy would get duplicated.  I stopped this behaviour by only giving this particular api key only read privileges.  Is there any way to fix this?  It would be great to be able to add notes or add references without worrying about duplicating existing records.

**Comment by Zaxim** [comment]
I'm not seeing this in the Zandy I downloaded from the Play store, but I am seeing it in the Zandy that I build with the latest master (e94625d1e172cd84ec985c689db031e379399a1d)
Anytime I edit a library item or an attachment, it doesn't modify it, it uploads multiple copies of it.

**Comment by mattrob33** [comment]
Same here. Looks like the latest master is not as recent as the version on the Play Store.
