### ISSUE TITLE
wrong extension for downloaded PDFs

### ISSUE THREAD

**Issue by domi84** [avram/zandy#98]
As written here:
http://www.gimranov.com/forum/index.php?p=/discussion/39/wrong-extension-for-downloaded-pdfs

I'm trying to download PDFs saved on my Zotero account for viewing in my android. When I download the attachment by doing a long tap on the "attachment" entry, it downloads the PDF but then the viewer gives a message that it's not a valid PDF file.

When I went to the folder on the SD card where the files are saved, it turns out that the problem is that they are saved with _PDF at the end (e.g. _MJW2SJV5Full_Text_PDF). When I change the _PDF to .PDF, the file opens correctly in the adobe reader.

I have this problem with Nexus 7 (Android 4.2.1) and Samsung Galaxy S (Android 2.3.5).

**Comment by avram** [comment]
Fixed here: https://github.com/avram/zandy/pull/136/commits/da719aa181885efc41cb89028ea15eddd786736d#diff-1715c862415f9f56455c0012cd9883d5R124
